### ISSUE TITLE
Creating emtpy cards is possible

### ISSUE THREAD

**Issue by martyschaer** [severinkaderli/memento#1]
name says it. One may create empty cards by clicking the "create" button without entering any information.

**Comment by severinkaderli** [comment]
Gonna take a look at this issue over the weekend. The Problem is that I'm not validating any forms for invalid input except the login and registering form.

**Comment by severinkaderli** [comment]
Well the bug is now fixed and there should be form validation in every form now, with nice looking error messages :)
